[package]
name = "ts3-query-api"
version = "0.2.0"
edition = "2021"

[dependencies]
flume = "0.11.0"
tokio = { version = "1.34.0", features = ["net", "rt", "time", "io-util", "macros", "rt-multi-thread"] }
log = "0.4.20"
env_logger = "0.10.1"
bytes = "1.5.0"
thiserror = "1.0.52"
