[package]
name = "ts3-query-api"
version = "0.1.0"
edition = "2021"

[dependencies]
flume = "0.11.0"
tokio = { version = "1.34.0", features = ["full"] }
log = "0.4.20"
env_logger = "0.10.1"
async-trait = "0.1.74"
